service: rubysls

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: ruby2.5

plugins:
  - serverless-plugin-aws-alerts

custom:
  alerts:
    stages:
      - production
    topics:
      alarm:
        topic: ${self:service}-${opt:stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: INSERT_YOUR_EMAIL
    alarms:
      - functionErrors
      - functionThrottles

functions:
  sleeper:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
